### ISSUE TITLE
thoughts on shapeless for marshalling

### ISSUE THREAD

**Issue by fommil** [mpollmeier/gremlin-scala#109]
I was discussing this with @joan38 today (we work at the same place, btw). It would be pretty easy to use shapeless to do all the marshalling of sealed traits / case classes into `Map[String, Any]` (I've already pretty much done it in https://github.com/fommil/ensime-server/blob/graph_indexer/core/src/main/scala/org/ensime/indexer/orientdb/SimpleOrient.scala which I might split out as an independent project as it appears reusable) and it would also be possible to use annotations to generate the implicits that customise the serialisation. I reckon it would mean a lot less coding for you if you just did marshalling this way, and in the v2 branch as well, of course :smile:

I might set this marshalling problem as a challenge in my scala exchange workshop next month, and worst case scenario I'll code something up over xmas.

**Comment by mpollmeier** [comment]
Sounds great! I'd also prefer a shapeless solution over macros. Here's a (probably non-complete) list of things the macro already does or could easily be extended to do, which the shapeless solution should cover as well:

1) Automatic unwrapping of Options and value classes. Maybe it would even make sense to generically unwrap classes with one member. E.g. if you have an `Option[A]`, then marshalling will take the inner value `A`, and unmarshalling constructs the `Option[A]`. This should be recursive.
Background: when you run OrientDB from within your JVM (as memory or plocal instance, rather than using `remote`) you can literally serialise everything - it will simply store it as the scala type. But that's a really bad idea because then only Scala clients will be able to deserialise them, and it doesn't work at all if you use the `remote` mode - Orient will simply say that it doesn't know anything about that type.  

2) Ability to annotate the case class with something like `@label("mylabel")` which can automatically be used when marshalling

3) Marshalling/unmarshalling the id to a case class member, e.g. with an annotation like the current `@id`. Ability to use an Option[Id]. 
Side note: we could gain some additional type safety if we ensure that the id is of the same type as the Graph's ID type (we could to add the ID type of the graph as a type argument to `ScalaGraph`). The macro version simply casts it to whatever is specified...
 
4) It might make sense to automatically convert Seq-like collection types into Arrays, which is more likely to be supported directly by whatever database is used. Similar to 1)

PS: I don't mind if we call it serialisation or marshalling.
PPS: the implementation would be 99% the same for V2 and V3 -> implicit win/win/win :)

**Comment by fommil** [comment]
All doable except we might need a macro to support each annotation, much simpler than new (it would just create an instance of an implicit typeclass with the customisation metadata)

**Comment by fommil** [comment]
fyi https://github.com/fommil/spray-json-shapeless/issues/15

**Comment by mpollmeier** [comment]
extra requirement: 
5) Ability to lookup the label for a case class at runtime, e.g. so that you can do `graph.V.hasLabel[MyCaseClass]` which looks up the label and  `hasLabel(labelOfCaseClass)`. 
I've just added some dirty reflection to make that work for the current makro implementation.

**Comment by fommil** [comment]
Typeable
