### ISSUE TITLE
Type error in `union` when using typesafe value keys.

### ISSUE THREAD

**Issue by metasim** [mpollmeier/gremlin-scala#129]
The type signature of `GremlinScala.union` requires one or more anonymous `GremlinScala` traversals. When wrapping the `__` TinkerPop traversal constructor and wrapping it with `GremlinScala`, something about the types don't align to allow the use of typesafe keys. In the example below, if you change the type parameters of `Age` and `Lang` to `Vertex`, then it compiles (and runs, due to erasure I suppose), but `Age` and `Lang` are clearly not of type `Vertex`.

I've tried a number of explicit type parameter specifications and haven't been able to get it to work without either using `Vertex` as the type parameter, or resorting to string keys.

```scala
import gremlin.scala._
import org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerFactory

val g = TinkerFactory.createModern().asScala

val Age = Key[Int]("age")
val Lang = Key[String]("lang")

// This works...
g.V(4).in().value(Age).toList()
g.V(4).out().value(Lang).toList()

// This doesn't
val trav = g.V(4)
  .union(
    GremlinScala(__).in().value(Age),  // <--- Type error
    GremlinScala(__).out().value(Lang)
  ).path()
```

**Comment by mpollmeier** [comment]
you are right, the type signature for union was wrong and I fixed that in https://github.com/mpollmeier/gremlin-scala/commit/c43dcff7951a2fb736cbfcfdaa8af190f8dabfd2 - let me know what you think. Don't merge that to master as there's no proper test yet - just exploring...

Note that this only works (and makes sense) if all anonymous traversals end at the same type, otherwise you end up with `Any`. Do you have an actual use case for having mixed types like Int and String in one result set?

**Comment by metasim** [comment]
> Note that this only works (and makes sense) if all anonymous traversals end at the same type, otherwise you end up with Any. Do you have an actual use case for having mixed types like Int and String in one result set?

I'd expect the compiler to select the common upper type bounds. In this case it would be `Any`, but I could see the case where one traversal returns `Int` and the other `Float`, and expect `Number` to be the resulting type. Is that kind of type-fu possible?

**Comment by mpollmeier** [comment]
This type-fu might be possible if union step would work as several method invocations, however the way it's done now (and so that it's close to gremlin-groovy) the compiler can only infer `Any`. See https://github.com/mpollmeier/gremlin-scala/blob/7a65c8bfb506679ef6aeacef238816d2746ffdc7/gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala#L369:L377
