### ISSUE TITLE
Using `fold()` appears to break typed labels.

### ISSUE THREAD

**Issue by metasim** [mpollmeier/gremlin-scala#145]
The following has no result, nor is correctly typed:
```
def graph = TinkerFactory.createModern.asScala
graph.V(1).outE.as(b).label().fold().as(d).select((b, d))
```
See commit below for full context.

**Comment by metasim** [comment]
See https://github.com/metasim/gremlin-scala/commit/4384c47cbacad7f5f87a08507faaf673e1497209 for test case.

As a separate item, `fold()` should probably be changed to propagate a Scala list rather than a java.util one.

**Comment by mpollmeier** [comment]
does that example work in gremlin-groovy? I suspect it doesn't, because `fold` is a barrier step, so `select` to summon things before and after that barrier doesn't work in my understanding. 

I've been careful with converting java objects into scala ones, because that has a runtime cost, and potentially you might not need to do that (depending on your traversal/use case). Definitely not ideal, but there's always  `import collection.JavaConversions._` at hand. Thoughts?

**Comment by mpollmeier** [comment]
oh, and because a fold is a barrier step, it returns a   `GremlinScala[JList[End], HNil]`, i.e. it purposely clears the labels.

**Comment by metasim** [comment]
> I've been careful with converting java objects into scala ones, because that has a runtime cost, and potentially you might not need to do that (depending on your traversal/use case). Definitely not ideal, but there's always import collection.JavaConversions._ at hand. Thoughts?

I think being conservative with the conversions is the right move... I just now wonder if you should ever do the conversion since most are already familiar with `JavaConversions`. Probably wouldn't want to break existing code over that, but it's an interesting design decision that might deserve more thought.

**Comment by metasim** [comment]
Not a bug: `fold()`, as a barrier step, is supposed to clear labels.
