### ISSUE TITLE
Doesn't filter multi-valued property keys

### ISSUE THREAD

**Issue by suhalemk** [mpollmeier/gremlin-scala#19]
Just started using this library(using version 2.4.2), really like it so far. I see an issue when querying multi valued property, it returns empty result. Here's my simplified test case

Just started using this library(using version 2.4.2), so far looks awesome. I'm filtering vertices with multiple 'has' conditions, and it's working just fine, except when the property is multivalued, in which case it returns blank/empty results. 

gremlin> v = g.addVertex(["name":"John","alias":"J"])
gremlin> g.V
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>v[40004]
gremlin> g.v(40004).map
==>{name=John}
gremlin> g.v(40004).addProperty("alias","j")
==>e[1G3J-ape-1k][40004-alias->j]
gremlin> g.v(40004).addProperty("alias","J")
==>e[1G3L-ape-1k][40004-alias->J]
gremlin> g.v(40004).map
==>{alias=[J, j], name=John}
gremlin> g.commit()
==>null

object MultiValueTest extends App {
    val g: ScalaGraph = TitanFactory.open("/tmp/del")
    val works_pipeline = g.V.has("name", "John")
    val shouldwork_pipeline = g.V.has("alias", "j")
    println(works_pipeline.toList)  //prints List(v[40004])
    println(shouldwork_pipeline.toList) //prints List() -- it should return the same node
    g.shutdown()
}

**Comment by jeremysears** [comment]
Now that filterOnEnd is discouraged due to its use of lambdas, is there a suggested solution for this that will push the query down to the driver?

  @label(VWithArray.Label)
  case class VWithArray(values: Array[String]) extends DomainRoot
  object VWithArray {
    val Label = "com.example.VWithArray"
    val Values = Key[Array[String]]("values")
  }

    val graph = ... // a tinkergraph
    val fooArray = Array("Foo")
    val va1 = graph.addVertex(VWithArray(fooArray))
    val va2 =.graph.addVertex(VWithArray(Array("Foo", "Bar", "Baz")))
    val va3 = graph.addVertex(VWithArray(Array("Foo")))
    val va4 = graph.addVertex(VWithArray(fooArray))
    val va5 = graph.addVertex(VWithArray(Array("Zim", "Zam")))

    ctx.graph.V.has(VWithArray.Values, fooArray).count.head must_== 4 // Fails, and returns 1.  It looks like it's also using array identity, so fooArray != Array("Foo").

    ctx.graph.V(VWithArray.Label).value(VWithArray.Values).hasValue("Foo").count.head must_== 4 // Also fails, returning 0.

Thank you for this wonderful library!  Let me know if you would like me to submit a PR with a test case, or if there is any other way I can help.

**Comment by mpollmeier** [comment]
Multi properties are a bit under-documented and tested. 
Here's the relevant info from the reference docs: http://tinkerpop.apache.org/docs/current/reference/#vertex-properties

Firstly it's important to be clear about what exactly you're expecting to find. IMO `has(VWithArray.Values, fooArray)` should check that the values are exactly identical, i.e. I would expect it to find `va1` and `va4`, i.e. the count should be 2. As you mentioned, it seems to compare references rather than content, which I find surprising as well.

Anyway, I don't think that's too bad because you typically search for one or more values, and not compare the complete array. Since you're asserting `count.head must_== 4`, I'm assuming that's the case for you as well. 

Conceptually, your Key should be of type `Key[String]` and then you use `Cardinality.list`. 
I've added/updates a similar case to https://github.com/mpollmeier/gremlin-scala/blob/master/gremlin-scala/src/test/scala/gremlin/scala/ElementSpec.scala#L41-L52 which is the equivalent of your second query. 

Since you're offering help: additional test cases would help, and the whole typesafe concept of `Key` only really works with `value` at the moment, not `property`.

**Comment by jeremysears** [comment]
Thanks Michael.  I'll take a look.  If I can sort it out, I'll push up a PR.

And, thank you again for your tireless effort on this lib!
