### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by rtfpessoa** [mpollmeier/gremlin-scala#217]
I am currently doing some tests with a big database and I am experiencing huge performance problems due to the way I am using the API.

Currently I want to do this SQL query `SELECT * from V_Class1` in Java.
Initially I though this would be `graph.V.hasLabel("V_Class1")` but this is actually `SELECT * from V where label = V_Class1`.

I tried looking in the API for something like `getVerticesOfClass` as described here http://orientdb.com/docs/2.0/orientdb.wiki/Graph-Database-Tinkerpop.html but I cannot find anything similar. Am I missing something? Can you give me some guidance regarding this?

**Comment by mpollmeier** [comment]
This is really a question for the orient driver (https://github.com/orientechnologies/orientdb-gremlin/), since that's supposed to translate your query to the more efficient version as you suggested. The only suggestion I have is to try adding a property step to see if the query optimiser kicks in then. E.g. `.has(dummyProp, true)` where dummyProp is true for all V_Class1.

I actually started that driver back in the days, but now it's maintained by orienttechnologies. There's a few words on index usage in the readme.
