### ISSUE TITLE
outE.toList is java List

### ISSUE THREAD

**Issue by omidb** [mpollmeier/gremlin-scala#58]
I was playing with the wrapper, here something that happens in some places, for example here
```scala
gs.v(1).outE("friend").toList
```
the code returns a Java List, I found also sometime some function returns Java objects instead of scala object like ScalaVertex.

**Comment by mpollmeier** [comment]
Re Java List: I don't think so - the signature of toList clearly specifies a Scala List, not a Java list:
https://github.com/mpollmeier/gremlin-scala/blob/master/src/main/scala/com/tinkerpop/gremlin/scala/GremlinScala.scala#L19

Re Java objects: that's intentional - I don't want to wrap every Vertex in every step into a ScalaVertex, that would be a lot of runtime overhead. Instead there are implicit conversions from Vertex to ScalaVertex etc. Another option is to use value classes, but that's currently a dead end because ScalaVertex and ScalaEdge extend ScalaElement.
