### ISSUE TITLE
List all vertices along specific edges without target vertex.

### ISSUE THREAD

**Issue by max-leuthaeuser** [mpollmeier/gremlin-scala#61]
I want to get a Set (in a **directed**, **acyclic** graph) of all vertices starting by the vertex with property ```"label" == "A"```. Edges are always labeled with ```"edge"```.

Example Graph:
![example](https://lh5.googleusercontent.com/-fk74VnUBXgQ/VNC3uLLcWRI/AAAAAAAABe4/D43AGxtHLkI/w472-h97-no/example.png)

So the result should be:
``` ["A", "B", "C", "F", "D", "E"] ``` or ``` ["A", "B", "D", "E", "C", "F"] ```
Ordering does not matter. Its not a question about the shortest path. All vertices along all possible paths should be included in the resulting Set.

How would an appropriate traverser look like?

**Comment by mpollmeier** [comment]
The answer depends on the version of Gremlin - I'm not sure how this 
works with the latest RC7 and SNAPSHOT as Marko is iterating faster than 
I can keep up (any help highly appreciated!).

The shortest path example 
(https://github.com/mpollmeier/gremlin-scala-examples/blob/master/neo4j/src/test/scala/ShortestPathSpec.scala) 
has something similar:

```
val paths = auckland.as("a").outE.inV.jump(
to = "a",
jumpPredicate = { t: Traverser[Vertex] ⇒
t.loops < 6 &&
t.get.value[String]("name") != "Cape Reinga" &&
t.get.value[String]("name") != "Auckland"
}
).filter(_.value[String]("name") == "Cape Reinga").path.toList
```

You only care about the destination, not the path. Just leave out the 
path step, use toSet instead of toList and you should be done. Set's 
don't have any order anyway.
