### ISSUE TITLE
The query language 

### ISSUE THREAD

**Issue by danyaljj** [mpollmeier/gremlin-scala#95]
The graph definition is just sooo beautiful: 
```
paris --- "OneWayRoad" --> london
```
Although your query language is very ugly: 
```
import gremlin.scala._
import org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerFactory
val graph = TinkerFactory.createModern.asScala
val traversal = graph.V.as("a").out.value[String]("name").as("b").labelledPath
traversal.toList
```
Any idea to generalize the definition operators to the query syntax?

**Comment by mpollmeier** [comment]
Very true. I think there's plenty of room to improve and beautify the 
syntax of a traversal. Ideas and PRs welcome (the graph definition was a 
PR by @dkrieg).

At the same time we should try not to move away tooo far from the 
standard Tinkerpop3, so that the documentation still applies. At the 
least we should probably keep the step names.

**Comment by danyaljj** [comment]
I see. I might be able to do sth for that, I think. 
I will send a PR, in case I come up with an idea.

**Comment by joan38** [comment]
That was actually a [PR from me](https://github.com/mpollmeier/gremlin-scala/commit/adb4abf2a7a1098e32e586441419a4be202ca171) that has been improved by @dkrieg 
PR are welcomed.

**Comment by mpollmeier** [comment]
sorry @joan38 I mixed that up

**Comment by joan38** [comment]
No worries @dkrieg did a great job that's why.
