### ISSUE TITLE
Marshalling for Option types

### ISSUE THREAD

**Issue by mpollmeier** [mpollmeier/gremlin-scala#98]
I've just used the `Marshallable` macro and was thinking that we could improve the Scala Option support. Here's my thoughts:
Let's say I have `case class Person(name: String, age: Option[Int])`

When I persist that, the database needs to know the type scala.Option (and it's subtypes). I tried it with OrientDB and got the following exception when I tried to persist it using a remote instance (i.e. using the remote protocol): 
```
Cause: com.orientechnologies.orient.core.exception.ODatabaseException: Error on deserialization of Serializable
Cause: java.lang.ClassNotFoundException: scala.Some
```

Adding scala-lang.jar to orient's lib directory works, but isn't really a nice solution. When persisting a value of `Some(42)` orient actually saves the serialised class. i.e. only scala will be able to deserialise it! 

IMO it would make sense to just persist `42`, and translate `None` into `null`

Another benefit of this would be that the schema can actually be flexible and evolve. Say we start without the `age` property, we could simply set `age` as we find it out about every person and represent it as Option[Int]. Again, if age is not set, serialise to None. 

@joan38 @omidb what do you guys think?

**Comment by joan38** [comment]
Hi,

That is exactly how I implemented that in the first (non macro) version.
I can take care of that if you guys are ok.

Cheers

**Comment by mpollmeier** [comment]
That would be awesome.

**Comment by mpollmeier** [comment]
I've implemented this in https://github.com/mpollmeier/gremlin-scala/compare/macro-option

**Comment by mpollmeier** [comment]
could be nicer though:
`_fromCCParams :+ q"""cc.$name.map{ name => $decoded -> name }.getOrElse("__gs" -> "")""",`
that `getOrElse` is only there because I can't add null to the sequence. I tried to use `++` and return `Nil` in the `None` case, but that didn't work

**Comment by dantodor** [comment]
FWIW, I have fought the same issue, and found this piece of code to be
useful:

trait CaseClassReflector extends Product {

def getFields = getClass.getDeclaredFields.map(field => {
field setAccessible true
field.getName -> field.get(this)
})

def getDefinedFields = {
(for ( (k,v) <- getFields.toMap if(v!=None)) yield (k,v))collect {
case (key, Some(value)) => key -> value
case (key, value ) => key -> value
}
}

def save (g:Graph): ScalaVertex = {

val fields = getDefinedFields
val vertex =
g.asScala.addVertex(fields.filter(!_._2.isInstanceOf[CaseClassReflector]))

getParents match {
case Some(v) => v.map(_.addEdge("is_parent_of",vertex))
case None => ()
}


for ( (k,v)<-fields if v.isInstanceOf[CaseClassReflector]) vertex.addEdge(
"is_parent_of",v.asInstanceOf[CaseClassReflector].save(g))

vertex
}

def getParents: Option[List[ScalaVertex]] = {
None
}
}

I derive then all my case classes from this trait. And if needed, some must
override the getParents ( identified by IDs by example in the case class)
in order to save the upstream relatioships. I agree that it's a less
elegant solution than the one with macros, since reflection comes with it's
own penalty, but on the bright side it saves basic data in node attributes
and embedded case classes in child nodes, recursively. I don't have the
case yet, but just noticed that it won't save correctly if I have a
List[CaseClassReflector], but I think it can be added relatively easy. And
speaking about null values, in my latest experiments with OrientDB,
probably no more than a month ago, it won't allow null value for vertex
properties, thus the code for filtering out None and transformig Some in
value.

I'm new to gremlin, so any oppinion is more than welcomed :)

Thanks!


All best,
Dan


Highlander getSingletonInstance() // there can only be one.

On Wed, Oct 28, 2015 at 6:06 AM, Michael Pollmeier <notifications@github.com

**Comment by mpollmeier** [comment]
Thanks for sharing, Dan. Always good to have another solution up your sleeve in case something doesn't work with the macro. 
There's also @omidb's marshalling solution using shapeless: https://github.com/mpollmeier/gremlin-scala/commit/31ef226

**Comment by mpollmeier** [comment]
sorted out in latest master
